---
apiVersion: v1
kind: Service
metadata:
  name: fahc
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: fahc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fahc
spec:
  selector:
    matchLabels:
      app: fahc
  replicas: 1
  template:
    metadata:
      labels:
        app: fahc
    spec:
      containers:
        - name: fahc
          image: ghcr.io/ebiiim/fah-collector:2.1.0
          command:
            - "./main"
            - "-refresh"
            - "1.0s"
            - "-clientDropTimer"
            - "3.0s"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
